# ???? ?????? ?? ????? ???-??????????, ?? ?????? ?????????
spring.main.web-application-type=none

# ????????? RabbitMQ
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.username=course_user
spring.rabbitmq.password=course_password
rabbitmq.exchange.name=chat.events.exchange

# ????????? gRPC ??????? (???? ?????????)
grpc.server.host=localhost
grpc.server.port=9091