server.port=8081

spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.username=course_user
spring.rabbitmq.password=course_password

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.multiplier=2.0

spring.rabbitmq.listener.simple.missing-queues-fatal=false