services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: chat-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: course_user
      RABBITMQ_DEFAULT_PASS: course_password

  postgres:
    image: postgres:15-alpine
    container_name: chat-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: chat_db

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: chat-keycloak
    command: start-dev --import-realm
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin-dev-only
    ports:
      - "8085:8080"
    volumes:
      - ./keycloak/course-realm.json:/opt/keycloak/data/import/course-realm.json:ro