server.port=8089

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
springdoc.packages-to-scan=org.example.rest.controllers

rabbitmq.exchange.name=chat.events.exchange

# ----------------------------------------
# PostgreSQL Database Configuration
# ----------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/chat_db
spring.datasource.username=chat_user
spring.datasource.password=qwerty

# ----------------------------------------
# JPA / Hibernate (Строго по заданию)
# ----------------------------------------
# Требование: отключаем транзакции на уровне view
spring.jpa.open-in-view=false
# Требование: Hibernate только проверяет схему, но не меняет ее (этим займется Flyway)
spring.jpa.hibernate.ddl-auto=validate

# Включаем логирование SQL-запросов (полезно для отладки)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ----------------------------------------
# Flyway Configuration
# ----------------------------------------
spring.flyway.enabled=true