server.port=8089

spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.username=course_user
spring.rabbitmq.password=course_password
springdoc.packages-to-scan=org.example.rest.controllers

rabbitmq.exchange.name=chat.events.exchange

spring.datasource.url=jdbc:postgresql://localhost:5432/chat_db
spring.datasource.username=chat_user
spring.datasource.password=qwerty

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8085/realms/course
spring.security.oauth2.resourceserver.jwt.audiences=recommendation-service